apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: service-bindings
spec:
  configPath: .data
  healthRule:
    alwaysHealthy: {}
  lifecycle: mutable
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    #@ load("@ytt:json", "json")
    #@ load("@ytt:struct", "struct")

    #@ def get_claims_extension():
    #@   claims_extension_key = "serviceclaims.supplychain.apps.x-tanzu.vmware.com/extensions"
    #@   if not hasattr(data.values.workload.metadata, "annotations") or not hasattr(data.values.workload.metadata.annotations, claims_extension_key):
    #@     return None
    #@   end
    #@
    #@   extension = json.decode(data.values.workload.metadata.annotations[claims_extension_key])
    #@
    #@   spec_extension = extension.get('spec')
    #@   if spec_extension == None:
    #@     return None
    #@   end
    #@
    #@   return spec_extension.get('serviceClaims')
    #@ end

    #@ def merge_claims_extension(claim, claims_extension):
    #@   if claims_extension == None:
    #@     return claim.ref
    #@   end
    #@   extension = claims_extension.get(claim.name)
    #@   if extension == None:
    #@      return claim.ref
    #@   end
    #@   extension.update(claim.ref)
    #@   return extension
    #@ end

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def merge_annotations(fixed_values):
    #@   annotations = {}
    #@   if hasattr(data.values.workload.metadata, "annotations"):
    #@     # DEPRECATED: remove in a future release
    #@     annotations.update(data.values.workload.metadata.annotations)
    #@   end
    #@   if type(param("annotations")) == "dict" or type(param("annotations")) == "struct":
    #@     annotations.update(param("annotations"))
    #@   end
    #@   annotations.update(fixed_values)
    #@   return annotations
    #@ end

    #@ def claims():
    #@ claims_extension = get_claims_extension()
    #@ for file in data.values.configs.app_def.config:
    #@ for obj in data.values.configs.app_def.config[file].split("\n---\n"):
    #@ pod_runner = struct.encode(yaml.decode(obj))
    #@ if not (hasattr(pod_runner, "metadata") and hasattr(pod_runner.metadata, "annotations")):
    #@   continue
    #@ end
    #@ if not hasattr(pod_runner.metadata.annotations, "ootb.apps.tanzu.vmware.com/servicebinding-workload"):
    #@   continue
    #@ end
    #@ if not pod_runner.metadata.annotations["ootb.apps.tanzu.vmware.com/servicebinding-workload"]:
    #@   continue
    #@ end
    ---
    apiVersion: kapp.k14s.io/v1alpha1
    kind: Config
    waitRules:
    - conditionMatchers:
      - type: ServiceAvailable
        status: "False"
        failure: true
      - type: ServiceAvailable
        status: "True"
        success: true
      resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: servicebinding.io/v1alpha3
          kind: ServiceBinding
    #@ for s in data.values.workload.spec.serviceClaims:
    #@ if claims_extension == None or claims_extension.get(s.name) == None:
    ---
    apiVersion: servicebinding.io/v1alpha3
    kind: ServiceBinding
    metadata:
      name: #@ data.values.workload.metadata.name + '-' + s.name
      annotations: #@ merge_annotations({"kapp.k14s.io/change-group": "servicebinding.io/ServiceBindings"})
      labels: #@ merge_labels({ "app.kubernetes.io/component": "run", "carto.run/workload-name": data.values.workload.metadata.name })
    spec:
      name: #@ s.name
      service: #@ s.ref
      workload:
        apiVersion: #@ pod_runner.apiVersion
        kind: #@ pod_runner.kind
        name: #@ pod_runner.metadata.name
    #@ else:
    ---
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    metadata:
      name: #@ data.values.workload.metadata.name + '-' + s.name
      annotations: #@ merge_annotations({})
      labels: #@ merge_labels({ "app.kubernetes.io/component": "run", "carto.run/workload-name": data.values.workload.metadata.name })
    spec:
      ref: #@ merge_claims_extension(s, claims_extension)
    ---
    apiVersion: servicebinding.io/v1alpha3
    kind: ServiceBinding
    metadata:
      name: #@ data.values.workload.metadata.name + '-' + s.name
      annotations: #@ merge_annotations({"kapp.k14s.io/change-group": "servicebinding.io/ServiceBindings"})
      labels: #@ merge_labels({ "app.kubernetes.io/component": "run", "carto.run/workload-name": data.values.workload.metadata.name })
    spec:
      name: #@ s.name
      service:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: #@ data.values.workload.metadata.name + '-' + s.name
      workload:
        apiVersion: #@ pod_runner.apiVersion
        kind: #@ pod_runner.kind
        name: #@ pod_runner.metadata.name
    #@ end
    #@ end
    #@ end
    #@ end
    #@ end

    #@ def add_claims():
    #@ if hasattr(data.values.workload.spec, "serviceClaims") and len(data.values.workload.spec.serviceClaims) > 0:
    #@    new_data = struct.decode(data.values.configs.app_def.config)
    #@    new_data.update({"serviceclaims.yml": yaml.encode(claims())})
    #@    return new_data
    #@ else:
    #@    return struct.decode(data.values.configs.app_def.config)
    #@ end
    #@ end

    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ data.values.workload.metadata.name + "-with-claims"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "config" })
    data: #@ add_claims()
