#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#! This if condition ensures that this Java Tekton pipeline is only created if the supply chain is testing or 
#! testing_scanning, the TAP profile used is full, iterate or build and pipeline parameter exists with value java.
#@ if/end in_list('supply_chain', ['testing', 'testing_scanning']) and in_list('profile', ['full', 'iterate', 'build']) and hasattr(data.values, 'pipeline') and data.values.pipeline == 'python':
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-pipeline-python
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: python
spec:
  params:
    - name: source-url                       
    - name: source-revision                  
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: python:3.10.8
            script: |-
              echo "+++ python version"
              python --version
              echo "+++ Make temp area"
              cd `mktemp -d`
              echo "+++ unpacking source"
              wget -qO- $(params.source-url) | tar xvz -m
              echo "+++ install requirements"
              pip install -r requirements.txt
              echo "+++ run pytest"
              python -m pytest

              